services:
  # Development application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_remote_node
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=dev
    volumes:
      # Mount source code for hot reload
      - ./server:/app/server
      - ./tsconfig.json:/app/tsconfig.json
      - ./eslint.config.js:/app/eslint.config.js
      - ./config:/app/config
    restart: no
